import type { Metadata } from "next";

import type { PublicEvent, PublicProgram } from "./api";
import { CONTACT, SITE_DESCRIPTION, SITE_NAME, absoluteUrl } from "./site";

/** Generated by app/opengraph-image.tsx. It carries no price, and must never. */
export const DEFAULT_SHARE_IMAGE = {
  url: absoluteUrl("/opengraph-image"),
  width: 1200,
  height: 630,
  alt: "Antitect",
};

interface ShareInput {
  title: string;
  description: string;
  path: string;
  /** Absolute. Falls back to the default share image; og:image is never empty. */
  imageUrl?: string | null;
  imageAlt?: string;
}

/**
 * Everything a WhatsApp preview reads, built through the Metadata API so
 * admin-authored titles are escaped for us. Nested fields such as `openGraph`
 * replace the layout's rather than merging, so each page sets all of them.
 *
 * Never pass a price in `description`: previews are cached long after it changes.
 */
export function shareMetadata({ title, description, path, imageUrl, imageAlt }: ShareInput): Metadata {
  const url = absoluteUrl(path);
  const image = imageUrl ? { url: imageUrl, alt: imageAlt ?? title } : DEFAULT_SHARE_IMAGE;

  return {
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_NG",
      url,
      title,
      description,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image.url],
    },
  };
}

// ---------------------------------------------------------------------------
// Structured data. Rendered with <JsonLd>, which escapes "<" so an
// admin-authored title cannot close the script tag.
// ---------------------------------------------------------------------------

type Json = Record<string, unknown>;

const organizationRef = { "@type": "Organization", name: SITE_NAME, url: absoluteUrl("/") };

export function organizationJsonLd(): Json {
  return {
    "@context": "https://schema.org",
    "@type": "EducationalOrganization",
    name: SITE_NAME,
    url: absoluteUrl("/"),
    logo: absoluteUrl("/icon.svg"),
    description: SITE_DESCRIPTION,
    email: CONTACT.email,
    telephone: CONTACT.phoneHref.replace("tel:", ""),
    address: {
      "@type": "PostalAddress",
      addressLocality: CONTACT.address.locality,
      addressRegion: CONTACT.address.region,
      addressCountry: CONTACT.address.country,
    },
  };
}

export function eventJsonLd(event: PublicEvent): Json {
  const url = absoluteUrl(`/events/${event.slug}`);
  const location =
    event.format === "in_person" && event.venue
      ? { "@type": "Place", name: event.venue.name, address: event.venue.address }
      : { "@type": "VirtualLocation", url };

  return {
    "@context": "https://schema.org",
    "@type": "Event",
    name: event.title,
    description: event.description,
    startDate: event.startsAt,
    ...(event.endsAt ? { endDate: event.endsAt } : {}),
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode:
      event.format === "in_person"
        ? "https://schema.org/OfflineEventAttendanceMode"
        : "https://schema.org/OnlineEventAttendanceMode",
    location,
    ...(event.imageUrl ? { image: [event.imageUrl] } : {}),
    organizer: organizationRef,
    offers: {
      "@type": "Offer",
      url,
      price: (event.priceKobo / 100).toFixed(2),
      priceCurrency: event.currency,
      availability: event.isFull ? "https://schema.org/SoldOut" : "https://schema.org/InStock",
    },
  };
}

export function courseJsonLd(program: PublicProgram): Json {
  return {
    "@context": "https://schema.org",
    "@type": "Course",
    name: program.title,
    description: program.summary,
    url: absoluteUrl(`/programmes/${program.slug}`),
    provider: organizationRef,
    ...(program.imageUrl ? { image: [program.imageUrl] } : {}),
    offers: {
      "@type": "Offer",
      price: (program.priceKobo / 100).toFixed(2),
      priceCurrency: program.currency,
      category: "Paid",
    },
    hasCourseInstance: {
      "@type": "CourseInstance",
      courseMode: "Online",
      ...(program.startsAt ? { startDate: program.startsAt } : {}),
      ...(program.durationWeeks ? { courseWorkload: `P${program.durationWeeks}W` } : {}),
    },
  };
}
